version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VUE_APP_API_URL=http://localhost:8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
    environment:
      - JWT_SECRET=logpilot_secret_key
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRY_MINUTES=60

  fluent-bit:
    image: fluent/fluent-bit:latest
    volumes:
      - ./config/fluent-bit:/fluent-bit/etc
      - ./logs:/logs
    ports:
      - "2020:2020"
